//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainFrame.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MainFrame.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   530 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ACOUNT_ERROR {
            get {
                return ResourceManager.GetString("ACOUNT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   HOSTのアカウントを確認してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ACOUNT_ERROR_MESSAGE {
            get {
                return ResourceManager.GetString("ACOUNT_ERROR_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CONFIRM に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CONFIRM {
            get {
                return ResourceManager.GetString("CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   の名前でフォルダを生成しますか？ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConFirm_MessageCont {
            get {
                return ResourceManager.GetString("ConFirm_MessageCont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   に接続 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERROR {
            get {
                return ResourceManager.GetString("ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   項目が見つかりません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERROR_NOTSEARCH {
            get {
                return ResourceManager.GetString("ERROR_NOTSEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   .fjm に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EXT_FJM {
            get {
                return ResourceManager.GetString("EXT_FJM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   .fjs に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EXT_FJS {
            get {
                return ResourceManager.GetString("EXT_FJS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   品種を取得できませんでした。FJMファイル名をご確認ください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FJM_FILETYPE_ERROR {
            get {
                return ResourceManager.GetString("FJM_FILETYPE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FTPサーバーに接続できません。
        ///設定メニューでサーバーのアドレスやアップロードパスをご確認ください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HOST_CONNECT_ERROR {
            get {
                return ResourceManager.GetString("HOST_CONNECT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   解決 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IP_ERROR {
            get {
                return ResourceManager.GetString("IP_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   HOSTのIPを確認してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string IP_ERROR_MESSAGE {
            get {
                return ResourceManager.GetString("IP_ERROR_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FJS又はFJMの拡張子がありません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NEC {
            get {
                return ResourceManager.GetString("NEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   未接続 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotConnect {
            get {
                return ResourceManager.GetString("NotConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ログインされていません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NOTLOGIN {
            get {
                return ResourceManager.GetString("NOTLOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OVERLAP ERROR に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OVERLAPERROR {
            get {
                return ResourceManager.GetString("OVERLAPERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ファイルを一つ選んでください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SEC {
            get {
                return ResourceManager.GetString("SEC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SELECT ERROR に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SELECTERROR {
            get {
                return ResourceManager.GetString("SELECTERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FTPサーバーにログインできません。
        ///設定メニューでユーザー名又はパスワードをご確認ください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SERVER_LOGIN_ERROR {
            get {
                return ResourceManager.GetString("SERVER_LOGIN_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   登録できませんでした。下記の内容をご確認ください。
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TRANCE_TYPEMISS_ERROR {
            get {
                return ResourceManager.GetString("TRANCE_TYPEMISS_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   550 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UPLOADPATH_ERROR {
            get {
                return ResourceManager.GetString("UPLOADPATH_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   HOSTのアプロードパスを確認してください に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UPLOADPATH_ERROR_MESSAGE {
            get {
                return ResourceManager.GetString("UPLOADPATH_ERROR_MESSAGE", resourceCulture);
            }
        }
    }
}
