//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mem_hkj {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class IOText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IOText() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("mem_hkj.IOText", typeof(IOText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   すべてのファイル (*.*) | *.*; | テキストファイル (*.txt) | *.txt과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ALLFILE {
            get {
                return ResourceManager.GetString("ALLFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   チェック과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string CHECK {
            get {
                return ResourceManager.GetString("CHECK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   名前を付けて保存과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DIALOG_TITLE {
            get {
                return ResourceManager.GetString("DIALOG_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   C://FormTestFile과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string DIRECTORY {
            get {
                return ResourceManager.GetString("DIRECTORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   『チェック』の項目ではありません。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ERROR_CHECK {
            get {
                return ResourceManager.GetString("ERROR_CHECK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   致命的なえらー $ファイル形式があたらないです。$과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ERROR_CONTENTS {
            get {
                return ResourceManager.GetString("ERROR_CONTENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   『英数字』のみ入力してください。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ERROR_ENGNUM_1 {
            get {
                return ResourceManager.GetString("ERROR_ENGNUM_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   『英数字入力』の最大数が超えました。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ERROR_ENGNUM_2 {
            get {
                return ResourceManager.GetString("ERROR_ENGNUM_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   『プルダウン』の項目ではありません。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ERROR_FULLDOWN {
            get {
                return ResourceManager.GetString("ERROR_FULLDOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エラ―メッセージ과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ERROR_MESSAGE {
            get {
                return ResourceManager.GetString("ERROR_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   『数字』のみ入力してください과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ERROR_NUMBER_1 {
            get {
                return ResourceManager.GetString("ERROR_NUMBER_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   『数字入力』の最大数が超えました。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ERROR_NUMBER_2 {
            get {
                return ResourceManager.GetString("ERROR_NUMBER_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   『ラジオ』の項目ではありません。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ERROR_RADIO {
            get {
                return ResourceManager.GetString("ERROR_RADIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   『ページ番号』の形式ではありません。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ERROR_SERIAL {
            get {
                return ResourceManager.GetString("ERROR_SERIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   『テキスト』の最大数が超えました。과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string ERROR_TEXT {
            get {
                return ResourceManager.GetString("ERROR_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   txt과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string EXT {
            get {
                return ResourceManager.GetString("EXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   項目과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FULLDOWN {
            get {
                return ResourceManager.GetString("FULLDOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   左과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string LEFT {
            get {
                return ResourceManager.GetString("LEFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   が修正されました。
        ///保存しますか？과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MODIFIEDBOX_CONTENTS {
            get {
                return ResourceManager.GetString("MODIFIEDBOX_CONTENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   修正保存確認과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MODIFIEDBOX_TITLE {
            get {
                return ResourceManager.GetString("MODIFIEDBOX_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   右과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RIGHT {
            get {
                return ResourceManager.GetString("RIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [a-zA-Z0-9]과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RX_ENGNUM {
            get {
                return ResourceManager.GetString("RX_ENGNUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [0-9]과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RX_NUMBER {
            get {
                return ResourceManager.GetString("RX_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (P)(19|20)\d{2}(0[1-9]|1[012])(0[1-9]|[12][0-9]|3[01])(0[0-9]|1[0-9]|2[0-3])([0-5][0-9])([0-5][0-9])과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string RX_SERIAL {
            get {
                return ResourceManager.GetString("RX_SERIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   がまだ保存されてないです。
        ///保存しますか？과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SAVEBOX_CONTENTS {
            get {
                return ResourceManager.GetString("SAVEBOX_CONTENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新規保存確認과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string SAVEBOX_TITLE {
            get {
                return ResourceManager.GetString("SAVEBOX_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   【新規】과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TAIL_NEW {
            get {
                return ResourceManager.GetString("TAIL_NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   txtNum과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TEXT_NUMBER {
            get {
                return ResourceManager.GetString("TEXT_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   txtNumEng과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TEXT_NUMENG {
            get {
                return ResourceManager.GetString("TEXT_NUMENG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   txtText과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TEXT_SERIAL {
            get {
                return ResourceManager.GetString("TEXT_SERIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ページ総数과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TOTALPAGE {
            get {
                return ResourceManager.GetString("TOTALPAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エニテック課題Ver.0.1과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string VERSION_LABEL {
            get {
                return ResourceManager.GetString("VERSION_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   バージョン情報과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string VERSION_TITLE {
            get {
                return ResourceManager.GetString("VERSION_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   【修正中】과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string WORKING {
            get {
                return ResourceManager.GetString("WORKING", resourceCulture);
            }
        }
    }
}
