SELECT TIME.HOUR, COUNT(TIME.HOUR)
FROM (SELECT EXTRACT (HOUR FROM CAST (DATETIME AS TIMESTAMP)) HOUR
     FROM ANIMAL_OUTS) TIME
WHERE TIME.HOUR  BETWEEN 9 AND 19
GROUP BY TIME.HOUR
ORDER BY TIME.HOUR;