SELECT A.HOUR
     , COUNT(B.DATETIME) AS COUNT
  FROM (SELECT LEVEL-1 AS HOUR
          FROM DUAL
       CONNECT BY LEVEL <=24) A
     , ANIMAL_OUTS B
 WHERE A.HOUR = TO_NUMBER(TO_CHAR(B.DATETIME(+), 'HH24'))
 GROUP
    BY A.HOUR
 ORDER
    BY A.HOUR